[package]
edition = "2021"
name = "sargabot"
version = "0.1.0"

[dependencies]
anyhow = "1.0.57"
egg-mode = "0.16.0"
rand = "0.8.5"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "1", features = ["full"]}
